# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.1
_src_path: https://github.com/jupyterlab/extension-template
author_email: konrad.jelen@gmail.com
author_name: Stellars Henson
has_ai_rules: false
has_binder: false
has_settings: true
kind: frontend-and-server
labextension_name: jupyterlab_server_proxy_launcher_fix
project_short_description: Fix to the issue that when launchers configured in the
    jupyter config file with svg icons are in a different category than notebooks,
    icons are not displayed. Also the new browser tab setting is ignored and launcher
    opens proxy in a separate browser tab
python_name: jupyterlab_server_proxy_launcher_fix
repository: ''
test: true

